{% set version = '0.19-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-coda
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/coda_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/coda/coda_{{ version }}.tar.gz
  sha256: 678a7e6a87a2723089daeb780ea37ac3d4319b37eabe26928ea3fa9c9b1eda0d

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-lattice
  run:
    - r-base
    - r-lattice

test:
  commands:
    - $R -e "library('coda')"           # [not win]
    - "\"%R%\" -e \"library('coda')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=coda
  license: GPL (>= 2)
  summary: Provides functions for summarizing and plotting the output from Markov Chain Monte
    Carlo (MCMC) simulations, as well as diagnostic tests of convergence to the equilibrium
    distribution of the Markov chain.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: coda
# Version: 0.19-2
# Date: 2018-10-08
# Title: Output Analysis and Diagnostics for MCMC
# Authors@R: c(person("Martyn", "Plummer", role=c("aut","cre","trl"), email="martyn.plummer@gmail.com"), person("Nicky", "Best", role="aut"), person("Kate", "Cowles", role="aut"), person("Karen", "Vines", role="aut"), person("Deepayan", "Sarkar", role="aut"), person("Douglas", "Bates", role="aut"), person("Russell", "Almond", role="aut"), person("Arni", "Magnusson", role="aut"))
# Depends: R (>= 2.14.0)
# Imports: lattice
# Description: Provides functions for summarizing and plotting the output from Markov Chain Monte Carlo (MCMC) simulations, as well as diagnostic tests of convergence to the equilibrium distribution of the Markov chain.
# License: GPL (>= 2)
# NeedsCompilation: no
# Packaged: 2018-10-08 10:16:54 UTC; martyn
# Author: Martyn Plummer [aut, cre, trl], Nicky Best [aut], Kate Cowles [aut], Karen Vines [aut], Deepayan Sarkar [aut], Douglas Bates [aut], Russell Almond [aut], Arni Magnusson [aut]
# Maintainer: Martyn Plummer <martyn.plummer@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-10-08 12:00:15 UTC
