appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: s5U+WTP4r2gMpbBAMsJLYLThrCHNEw/xlqlyhB/pBQk/YMNbqBdZsOM09L2fpriLiKaRGUy3glTKnDSMEHPNyTwFYRYuPt7R+B8QLZMtS+g/0y7wANjARyeT9EFsAQAfb1WpIBpCSq4usWlGJIaTRj5MlZZddTbGPquWW6xPOaaS4CfMStY9KBxVOGHZYBHjZDSn+iYX1/I2PK2DclBZyfgUfiYxpQIN3ahQICvEMHP3tK9g+JZCbnC/vRk3ex70dhkbW/M3I/wWoaiUgSg8WcjJS4AUa9Yy8DIdPZmJXEL3hXNEpWHSU5WQOOywbSd1sv4YvoGWHZWqGAejIXa6/hotd+23T/Z/ycwY7MTSKFWQ86Xpn0GqTFJwvI+vW2zFDTGPY7+J8wbElbRR+G4ZnE1+6DjgSYOY/LF6+MHxuqm3yM6SJ9vXY+i0lvKULv0gMpIlSbN0lHIEOluH6XPS1rEploQMBuqqhCktH/PEHvwA6FMT9FdQ9w1q1tQ/RRd8jIoWL+lA0f3DS/8u0yrHO0oOVHEuAD+cp6DZ0AZpQRB/aDQBPZIB36MT1Wrbwsjgd4FEnyIKipEzuluKe+y4lj6fG/6CzciozZM5Br8WnZrAktX8+pLkYXLGbUus3ikr66i6HfENLlCZsMQClorNi9awYkYu2DSUH2hRlVHQgsQ=}
